apiVersion: 1

datasources:
  - name: Local TimescaleDB
    type: postgres
    uid: local-timescaledb
    access: proxy
    url: timescaledb:5432
    database: timescaledb
    user: anatoli
    secureJsonData:
      password: ''
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    editable: true
    isDefault: true
