apiVersion: 1

datasources:
  - name: Central TimescaleDB
    type: postgres
    uid: central-timescaledb
    access: proxy
    url: remote-timescaledb:5432
    database: bacnet_central
    user: anatoli
    secureJsonData:
      password: ''
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    editable: true
    isDefault: true
